version: '3'
services:
  api:
    build: .
    ports:
      - '8080:8080'
    expose:
      - '8080'

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
